version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: "/"
