name: Fix SonarCloud Issues with Pixeebot
on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload SonarQube Results to Pixeebot
        uses: pixee/upload-tool-results-action@v2
        if: always() && steps.sonarqube-analysis.outcome == 'success'
        with:
            tool: sonar
            sonar-host-url: ${{ vars.SONAR_HOST_URL }}
            sonar-token: ${{ secrets.SONAR_TOKEN }}
            sonar-component-key: "thomas-iniguez-visioli_vbcq"
